### ISSUE TITLE
Rework Rob to use classes

### ISSUE THREAD

**Issue by stijndcl** [stijndcl/didier#13]
Rob is a _huge_ mess and I'm a bit scared to touch it, but they should start using classes. These classes would store all info on a person's profile, with functions that make checks a lot easier to perform. The profiles can be built from the info in the database.

The actual `Rob` function will become a _lot_ cleaner.

Bank-related functions can also use these classes to clean up a bit.

**Comment by TheMessik** [comment]
I'll take this from here
