### ISSUE TITLE
didier pin

### ISSUE THREAD

**Issue by lars-vc** [stijndcl/didier#23]
Usage: `didier pin mesgID`
Didier will start a vote requiring x yeah votes for the message to be pinned in the current channel.
This will reduces admin spam for pins

**Comment by stijndcl** [comment]
I see how this is useful, but knowing you guys  I'm not sure if this is a good idea. There's a big chance I wake up in the morning with random stuff pinned after you make another react-hitsquad.

**Comment by NinjaJay** [comment]
I mean you could set the votes high enough, but I mean, let's be honest for react-hitsquad, we would only probably do it in the warzone channel, which shouldn't really be bother anyone. It is really usefull for the school channels.

**Comment by lars-vc** [comment]
Je shit might go down in fun channels but like jay said, we wont fuck around with the school channels
